#if !canImport(ObjectiveC)
import XCTest

extension BinaryTreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryTreeTests = [
        ("testConstructor", testConstructor),
        ("testConstructorFromJSON", testConstructorFromJSON),
        ("testEqualsSingleValue", testEqualsSingleValue),
        ("testEqualsTreeValues", testEqualsTreeValues),
        ("testInOrderTraversal", testInOrderTraversal),
        ("testPostOrderTraversal", testPostOrderTraversal),
        ("testPreOrderTraversal", testPreOrderTraversal),
    ]
}

extension DoublyLinkedListTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DoublyLinkedListTests = [
        ("testConstructor", testConstructor),
        ("testConstructorFromArray", testConstructorFromArray),
        ("testEqualsFromHead", testEqualsFromHead),
        ("testEqualsFromMiddle", testEqualsFromMiddle),
        ("testHead", testHead),
    ]
}

extension GraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GraphTests = [
        ("testConnectionForKey", testConnectionForKey),
        ("testConnectionsAreNotBidirectional", testConnectionsAreNotBidirectional),
        ("testConnectionsTraversal", testConnectionsTraversal),
        ("testConnectToSelf", testConnectToSelf),
        ("testReferencesAreEqual", testReferencesAreEqual),
        ("testShallowCompareValuesDifferentConnections", testShallowCompareValuesDifferentConnections),
        ("testShallowCompareValuesNoConnections", testShallowCompareValuesNoConnections),
        ("testShallowCompareValuesSameConnections", testShallowCompareValuesSameConnections),
        ("testValuesAreNotEqual", testValuesAreNotEqual),
    ]
}

extension LinkedListTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LinkedListTests = [
        ("testConstructor", testConstructor),
        ("testConstructorFromArray", testConstructorFromArray),
        ("testEqualsFromHead", testEqualsFromHead),
        ("testEqualsFromMiddle", testEqualsFromMiddle),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BinaryTreeTests.__allTests__BinaryTreeTests),
        testCase(DoublyLinkedListTests.__allTests__DoublyLinkedListTests),
        testCase(GraphTests.__allTests__GraphTests),
        testCase(LinkedListTests.__allTests__LinkedListTests),
    ]
}
#endif
